# Generated by Django 2.2.9 on 2020-03-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0014_catalogrecord_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='catalog_record_services_create',
            field=models.CharField(help_text='Services which are allowed to edit catalog records in the catalog.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datacatalog',
            name='catalog_record_services_edit',
            field=models.CharField(help_text='Services which are allowed to edit catalog records in the catalog.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datacatalog',
            name='catalog_record_group_create',
            field=models.CharField(help_text='Group which is allowed to add new catalog records to the catalog.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datacatalog',
            name='catalog_record_group_edit',
            field=models.CharField(help_text='Group which is allowed to edit catalog records in the catalog.', max_length=200, null=True),
        ),
    ]
