# Generated by Django 2.1.11 on 2020-04-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0018_auto_20200330_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='catalog_record_services_read',
            field=models.CharField(help_text='Services which are allowed to read catalog records in the catalog.', max_length=200, null=True),
        ),
    ]
