# Generated by Django 2.1.11 on 2020-04-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0019_datacatalog_catalog_record_services_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='catalog_record_group_read',
            field=models.CharField(help_text='Group which is allowed to read catalog records in the catalog.', max_length=200, null=True),
        ),
    ]
